apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc-mysql
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: mysql-after
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi