apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.backstore.github.com
spec:
  group: backstore.github.com
  names:
    plural: restores
    singular: restore
    kind: Restore
    shortNames:
      - rstr
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.progress
          name: Progress
          type: string
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                backup-name:
                  type: string
                volume-snapshot-class-name:
                  type: string
                storage:
                  type: string
            status:
              type: object
              properties:
                progress:
                  type: string

status: