apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.backstore.github.com
spec:
  group: backstore.github.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                backup-name:
                  type: string
                storage:
                  type: string
  names:
    plural: restores
    singular: restore
    kind: Restore
    shortNames:
      - rstr
  scope: Namespaced

